server:
  port: 8085


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-evento-service
          uri: lb://ms-evento-service
          predicates:
            - Path=/evento/**
        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/cliente/**
        - id: ms-inscripcion-service
          uri: lb://ms-inscripcion-service
          predicates:
            - Path=/inscripcion/**
